spring: 
  jpa: 
    hibernate: 
      ddl-auto: create
  datasource: 
    url: jdbc:mysql://localhost:3306/biblioteca
    username: username
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver